### ISSUE TITLE
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

### ISSUE THREAD

**Issue by miladkhademinori** [GMvandeVen/class-incremental-learning#5]
Got this error:

internals>", line 200, in argmax
  File "/home/19mkn1/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 1242, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out, **kwds)
  File "/home/19mkn1/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/home/19mkn1/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
  File "/home/19mkn1/.local/lib/python3.8/site-packages/torch/_tensor.py", line 678, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
srun: error: aurora: task 0: Exited with exit code 1

This error occurs in a Python script that is attempting to convert a PyTorch tensor to a NumPy array. However, the tensor is located on a CUDA device (i.e., GPU) rather than on the CPU. PyTorch doesn't support directly converting CUDA tensors to NumPy arrays because NumPy operates on CPU memory.

The error message specifically suggests using `Tensor.cpu()` to copy the tensor to host memory first, before converting it to a NumPy array. Here's how you can fix it:

```python
import torch

# Assuming 'cuda_tensor' is your PyTorch tensor on the CUDA device
cuda_tensor = torch.tensor([1, 2, 3]).cuda()

# Move the tensor to CPU
cpu_tensor = cuda_tensor.cpu()

# Now you can convert it to a NumPy array
numpy_array = cpu_tensor.numpy()
```

By first moving the tensor to the CPU using `cpu()`, you can then safely convert it to a NumPy array.

**Comment by miladkhademinori** [comment]
More information just in case:


<GENERATOR>  | Class: 99/100 | training loss: 0.199 |: 100%|██████████| 500/500 [00:33<00:00, 15.04it/s]
 <GENERATOR>  | Class: 100/100 | training loss: 0.202 |: --> saved model gC-CIFAR100-N--x100-VAE=C3-5x16-bn_F-1024x1000x1000_z100--i500-lr0.001-b256-MSE to ./store/models


EVALUATION RESULTS:

 Accuracy of final model on test-set:
 <GENERATOR>  | Class: 100/100 | training loss: 0.202 |: 100%|██████████| 500/500 [00:34<00:00, 14.56it/s]
Traceback (most recent call last):
  File "main_generative.py", line 371, in <module>
    run(args, verbose=True)
  File "main_generative.py", line 270, in run
    acc = evaluate.validate(model, test_datasets[i], verbose=False, allowed_classes=None, S=args.eval_s,
  File "/home/19mkn1/class-incremental-learning/eval/evaluate.py", line 46, in validate
    predicted = model.classify(x, S=S, batch_size=batch_size, allowed_classes=allowed_classes)
  File "/home/19mkn1/class-incremental-learning/models/gen_classsifier.py", line 112, in classify
    predicted = allowed_classes[np.argmax(scores)]
  File "<__array_function__ internals>", line 200, in argmax
  File "/home/19mkn1/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 1242, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out, **kwds)
  File "/home/19mkn1/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/home/19mkn1/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
  File "/home/19mkn1/.local/lib/python3.8/site-packages/torch/_tensor.py", line 678, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
srun: error: sasquatch: task 0: Exited with exit code 1

**Comment by miladkhademinori** [comment]
To fix the issue go to `gen_classsifier.py` line 112 instead of 

predicted = allowed_classes[np.argmax(scores)]

Add
scores_cpu = torch.stack(scores).cpu()  # Move scores to CPU
predicted = allowed_classes[np.argmax(scores_cpu.numpy())]  # Convert scores_cpu to numpy array after moving to CPU
